import { CompanyId, DataSourceId, DocumentId, DocumentStatus, MetaDocumentType, MetaEventDocument } from './index';

/**
 * Unique identifier for events. This is a 64-bit signed int represented as a string.
 * event_id's are globally unique and monotonic, meaning a higher event_id will always represent a newer event.
 * @example "665775325455589385"
 */
export type EventId = string;

/**
 * Represents an event generated by Smooth Integration system to represent the state of the SmoothIntegration system.
 * These can be used to track how up-to-date the SmoothIntegration system is with the external system.
 */
export type MetaEvent = {
    event_id: EventId;
    company_id: CompanyId;
    data_source_id: DataSourceId;
    document_id: undefined;
    document_type: MetaDocumentType;
    document_status: undefined;
    document: MetaEventDocument;
};

/**
 * Represents an event generated by Smooth Integration system to represent a change to a document in an external system.
 */
export type DocumentEvent = {
    event_id: EventId;
    company_id: CompanyId;
    data_source_id: DataSourceId;
    document_id: DocumentId;
    document_type: DocumentType;
    document_status: DocumentStatus;
    document: Document;
};

/**
 * Represents any event generated by Smooth Integration system.
 */
export type Event = MetaEvent | DocumentEvent;
